// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: cart_service.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartAddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sku           uint32                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartAddItemRequest) Reset() {
	*x = CartAddItemRequest{}
	mi := &file_cart_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartAddItemRequest) ProtoMessage() {}

func (x *CartAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartAddItemRequest.ProtoReflect.Descriptor instead.
func (*CartAddItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_proto_rawDescGZIP(), []int{0}
}

func (x *CartAddItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartAddItemRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *CartAddItemRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CartDeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sku           uint32                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartDeleteItemRequest) Reset() {
	*x = CartDeleteItemRequest{}
	mi := &file_cart_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartDeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartDeleteItemRequest) ProtoMessage() {}

func (x *CartDeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartDeleteItemRequest.ProtoReflect.Descriptor instead.
func (*CartDeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_proto_rawDescGZIP(), []int{1}
}

func (x *CartDeleteItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartDeleteItemRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type CartUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartUserIDRequest) Reset() {
	*x = CartUserIDRequest{}
	mi := &file_cart_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartUserIDRequest) ProtoMessage() {}

func (x *CartUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartUserIDRequest.ProtoReflect.Descriptor instead.
func (*CartUserIDRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_proto_rawDescGZIP(), []int{2}
}

func (x *CartUserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartListItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    uint32                 `protobuf:"varint,2,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListItemResponse) Reset() {
	*x = CartListItemResponse{}
	mi := &file_cart_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListItemResponse) ProtoMessage() {}

func (x *CartListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListItemResponse.ProtoReflect.Descriptor instead.
func (*CartListItemResponse) Descriptor() ([]byte, []int) {
	return file_cart_service_proto_rawDescGZIP(), []int{3}
}

func (x *CartListItemResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartListItemResponse) GetTotalPrice() uint32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_cart_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cart_service_proto_rawDescGZIP(), []int{4}
}

func (x *CartItem) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *CartItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CartItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItem) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_cart_service_proto protoreflect.FileDescriptor

const file_cart_service_proto_rawDesc = "" +
	"\n" +
	"\x12cart_service.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"U\n" +
	"\x12CartAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"B\n" +
	"\x15CartDeleteItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\rR\x03sku\",\n" +
	"\x11CartUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"[\n" +
	"\x14CartListItemResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.api.CartItemR\x05items\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x02 \x01(\rR\n" +
	"totalPrice\"\\\n" +
	"\bCartItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price2\xef\x02\n" +
	"\vCartService\x12U\n" +
	"\aAddItem\x12\x17.api.CartAddItemRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/cart/item/add\x12^\n" +
	"\n" +
	"DeleteItem\x12\x1a.api.CartDeleteItemRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/cart/item/delete\x12T\n" +
	"\bListItem\x12\x16.api.CartUserIDRequest\x1a\x19.api.CartListItemResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/cart/list\x12S\n" +
	"\tClearCart\x12\x16.api.CartUserIDRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/cart/clearB:Z8github.com/just-umyt/homework_all-just-umyt/cart/pkg/apib\x06proto3"

var (
	file_cart_service_proto_rawDescOnce sync.Once
	file_cart_service_proto_rawDescData []byte
)

func file_cart_service_proto_rawDescGZIP() []byte {
	file_cart_service_proto_rawDescOnce.Do(func() {
		file_cart_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_service_proto_rawDesc), len(file_cart_service_proto_rawDesc)))
	})
	return file_cart_service_proto_rawDescData
}

var file_cart_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cart_service_proto_goTypes = []any{
	(*CartAddItemRequest)(nil),    // 0: api.CartAddItemRequest
	(*CartDeleteItemRequest)(nil), // 1: api.CartDeleteItemRequest
	(*CartUserIDRequest)(nil),     // 2: api.CartUserIDRequest
	(*CartListItemResponse)(nil),  // 3: api.CartListItemResponse
	(*CartItem)(nil),              // 4: api.CartItem
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_cart_service_proto_depIdxs = []int32{
	4, // 0: api.CartListItemResponse.items:type_name -> api.CartItem
	0, // 1: api.CartService.AddItem:input_type -> api.CartAddItemRequest
	1, // 2: api.CartService.DeleteItem:input_type -> api.CartDeleteItemRequest
	2, // 3: api.CartService.ListItem:input_type -> api.CartUserIDRequest
	2, // 4: api.CartService.ClearCart:input_type -> api.CartUserIDRequest
	5, // 5: api.CartService.AddItem:output_type -> google.protobuf.Empty
	5, // 6: api.CartService.DeleteItem:output_type -> google.protobuf.Empty
	3, // 7: api.CartService.ListItem:output_type -> api.CartListItemResponse
	5, // 8: api.CartService.ClearCart:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cart_service_proto_init() }
func file_cart_service_proto_init() {
	if File_cart_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_service_proto_rawDesc), len(file_cart_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_service_proto_goTypes,
		DependencyIndexes: file_cart_service_proto_depIdxs,
		MessageInfos:      file_cart_service_proto_msgTypes,
	}.Build()
	File_cart_service_proto = out.File
	file_cart_service_proto_goTypes = nil
	file_cart_service_proto_depIdxs = nil
}
