// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: stock.proto

package stock

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockAddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sku           uint32                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockAddItemRequest) Reset() {
	*x = StockAddItemRequest{}
	mi := &file_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockAddItemRequest) ProtoMessage() {}

func (x *StockAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockAddItemRequest.ProtoReflect.Descriptor instead.
func (*StockAddItemRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockAddItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StockAddItemRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *StockAddItemRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StockAddItemRequest) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockAddItemRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type StockDeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sku           uint32                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockDeleteItemRequest) Reset() {
	*x = StockDeleteItemRequest{}
	mi := &file_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockDeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockDeleteItemRequest) ProtoMessage() {}

func (x *StockDeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockDeleteItemRequest.ProtoReflect.Descriptor instead.
func (*StockDeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockDeleteItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StockDeleteItemRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type StockListItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CurrentPage   int64                  `protobuf:"varint,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockListItemRequest) Reset() {
	*x = StockListItemRequest{}
	mi := &file_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockListItemRequest) ProtoMessage() {}

func (x *StockListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockListItemRequest.ProtoReflect.Descriptor instead.
func (*StockListItemRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{2}
}

func (x *StockListItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StockListItemRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *StockListItemRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *StockListItemRequest) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

type StockGetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockGetItemRequest) Reset() {
	*x = StockGetItemRequest{}
	mi := &file_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockGetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetItemRequest) ProtoMessage() {}

func (x *StockGetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetItemRequest.ProtoReflect.Descriptor instead.
func (*StockGetItemRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{3}
}

func (x *StockGetItemRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type StockListItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItemResponse   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageNumber    int64                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockListItemResponse) Reset() {
	*x = StockListItemResponse{}
	mi := &file_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockListItemResponse) ProtoMessage() {}

func (x *StockListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockListItemResponse.ProtoReflect.Descriptor instead.
func (*StockListItemResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{4}
}

func (x *StockListItemResponse) GetItems() []*StockItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *StockListItemResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *StockListItemResponse) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type StockItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint32                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItemResponse) Reset() {
	*x = StockItemResponse{}
	mi := &file_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItemResponse) ProtoMessage() {}

func (x *StockItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItemResponse.ProtoReflect.Descriptor instead.
func (*StockItemResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{5}
}

func (x *StockItemResponse) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *StockItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockItemResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StockItemResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StockItemResponse) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockItemResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *StockItemResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_stock_proto protoreflect.FileDescriptor

const file_stock_proto_rawDesc = "" +
	"\n" +
	"\vstock.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x01\n" +
	"\x13StockAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"C\n" +
	"\x16StockDeleteItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\rR\x03sku\"\x8b\x01\n" +
	"\x14StockListItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12!\n" +
	"\fcurrent_page\x18\x04 \x01(\x03R\vcurrentPage\"'\n" +
	"\x13StockGetItemRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\"\x87\x01\n" +
	"\x15StockListItemResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.api.StockItemResponseR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x03R\n" +
	"pageNumber\"\xae\x01\n" +
	"\x11StockItemResponse\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x05 \x01(\rR\x05price\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId2\xfc\x02\n" +
	"\fStockService\x12X\n" +
	"\aAddItem\x12\x18.api.StockAddItemRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/stocks/item/add\x12a\n" +
	"\n" +
	"DeleteItem\x12\x1b.api.StockDeleteItemRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/stocks/item/delete\x12Z\n" +
	"\bListItem\x12\x19.api.StockListItemRequest\x1a\x1a.api.StockListItemResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/stocks/list\x12S\n" +
	"\aGetItem\x12\x18.api.StockGetItemRequest\x1a\x16.api.StockItemResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/stocks/getB\x0fZ\rpkg/api/stockb\x06proto3"

var (
	file_stock_proto_rawDescOnce sync.Once
	file_stock_proto_rawDescData []byte
)

func file_stock_proto_rawDescGZIP() []byte {
	file_stock_proto_rawDescOnce.Do(func() {
		file_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)))
	})
	return file_stock_proto_rawDescData
}

var file_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stock_proto_goTypes = []any{
	(*StockAddItemRequest)(nil),    // 0: api.StockAddItemRequest
	(*StockDeleteItemRequest)(nil), // 1: api.StockDeleteItemRequest
	(*StockListItemRequest)(nil),   // 2: api.StockListItemRequest
	(*StockGetItemRequest)(nil),    // 3: api.StockGetItemRequest
	(*StockListItemResponse)(nil),  // 4: api.StockListItemResponse
	(*StockItemResponse)(nil),      // 5: api.StockItemResponse
	(*emptypb.Empty)(nil),          // 6: google.protobuf.Empty
}
var file_stock_proto_depIdxs = []int32{
	5, // 0: api.StockListItemResponse.items:type_name -> api.StockItemResponse
	0, // 1: api.StockService.AddItem:input_type -> api.StockAddItemRequest
	1, // 2: api.StockService.DeleteItem:input_type -> api.StockDeleteItemRequest
	2, // 3: api.StockService.ListItem:input_type -> api.StockListItemRequest
	3, // 4: api.StockService.GetItem:input_type -> api.StockGetItemRequest
	6, // 5: api.StockService.AddItem:output_type -> google.protobuf.Empty
	6, // 6: api.StockService.DeleteItem:output_type -> google.protobuf.Empty
	4, // 7: api.StockService.ListItem:output_type -> api.StockListItemResponse
	5, // 8: api.StockService.GetItem:output_type -> api.StockItemResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stock_proto_init() }
func file_stock_proto_init() {
	if File_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_proto_goTypes,
		DependencyIndexes: file_stock_proto_depIdxs,
		MessageInfos:      file_stock_proto_msgTypes,
	}.Build()
	File_stock_proto = out.File
	file_stock_proto_goTypes = nil
	file_stock_proto_depIdxs = nil
}
