services:
  cart_service:
    image: umyt/cart:hw7
    depends_on:
      cart_db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${SERVER_PORT}:8080"
    container_name: umyt/cart-service
    networks:
      - public-net
      - internal-net

  cart_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "${DB_PORT}:5432"
    container_name: umyt/cart-db
    networks:
      - internal-net

networks:
  public-net:
    external: true
  internal-net:
    driver: bridge
