services:
  cart_service:
    image: umyt/cart:hw10
    depends_on:
      cart_db:
        condition: service_healthy
    ports:
      - "8070:8070"
      - "8080:8080"
      - "8090:8090"
    container_name: umyt-cart-service
    networks:
      - public-net
      - internal-net

  cart_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cart"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    container_name: umyt-cart-db
    networks:
      - internal-net

networks:
  public-net:
    external: true
  internal-net:
    driver: bridge
