version: "3.9"

services:
  cart_service:
    build: .
    depends_on:
      cart_db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    container_name: umyt_cart-service
    networks:
      - app-network

  cart_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cart_service_db"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5433:${DB_PORT}"
    container_name: umyt_cart-db
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
