# Server configurations
server:
  host: "localhost"
  port: 8080
  readheadertimeout: 10
  shutdowntimeout: 3

client:
  url: "http://127.0.0.1:8081/stocks/item/get"
  timeout: 2

# Database credentials
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  name: "cart"
  sslmode: "disable"
  timeout: 30
