# Server configurations
server:
  host: "0.0.0.0"
  port: 8080
  readheadertimeout: 10
  shutdowntimeout: 3

#Client configurations
client:
  url: "http://localhost:8081/stocks/item/get"
  timeout: 2
