# Server configurations
server:
  host: "localhost"
  port: 8080
  readheadertimeout: 10
  shutdowntimeout: 3

client:
  url: "http://127.0.0.1:8081/stocks/item/get"
  timeout: 2

# Database credentials
database:
  dbhost: "localhost"
  dbport: 5432
  dbuser: "postgres"
  dbname: "homework"
  dbsslmode: "disable"
  timeout: 30
