{
 "title": "Homework 11",
 "description": "Default grafana dasboards to learn",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(http_failed_requests_total,path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Time series or table",
   "type": "timeseries",
   "description": "Understand the volume of requests behind latency metrics.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path, status) (rate(http_response_time_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Requests Rate (Per Second)",
   "type": "timeseries",
   "description": "Visualize the error rate trend over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, path, status) (rate(http_failed_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency (Per Path)",
   "type": "timeseries",
   "description": "Shows average response time trend for each route.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_response_time_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total failed requests (Counter)",
   "type": "stat",
   "description": "Shows total failed requests per route and method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path, method, status) (http_failed_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Latency (Over Time)",
   "type": "timeseries",
   "description": "Shows high-latency requests, grouped by path.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(http_response_time_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}